package psk1.assignment.myBatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import psk1.assignment.myBatis.model.Movie;

@Mapper
public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOVIE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOVIE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    int insert(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOVIE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    Movie selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOVIE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    List<Movie> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOVIE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    int updateByPrimaryKey(Movie record);
}