package psk1.assignment.myBatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import psk1.assignment.myBatis.model.Producer;

@Mapper
public interface ProducerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    int insert(Producer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    Producer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    List<Producer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PRODUCER
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    int updateByPrimaryKey(Producer record);
}