package psk1.assignment.myBatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import psk1.assignment.myBatis.model.Role;

@Mapper
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROLE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROLE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROLE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROLE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROLE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    int updateByPrimaryKey(Role record);
}