package psk1.assignment.myBatis.model;

import java.util.Date;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.ID
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.RELEASE_DATE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    private Date releaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.TITLE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.ID
     *
     * @return the value of PUBLIC.MOVIE.ID
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.ID
     *
     * @param id the value for PUBLIC.MOVIE.ID
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.RELEASE_DATE
     *
     * @return the value of PUBLIC.MOVIE.RELEASE_DATE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.RELEASE_DATE
     *
     * @param releaseDate the value for PUBLIC.MOVIE.RELEASE_DATE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.TITLE
     *
     * @return the value of PUBLIC.MOVIE.TITLE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.TITLE
     *
     * @param title the value for PUBLIC.MOVIE.TITLE
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }
}