package psk1.assignment.myBatis.model;

import java.util.Date;

public class Producer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCER.ID
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCER.DATE_OF_BIRTH
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCER.FIRST_NAME
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PRODUCER.LAST_NAME
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    private String lastName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCER.ID
     *
     * @return the value of PUBLIC.PRODUCER.ID
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCER.ID
     *
     * @param id the value for PUBLIC.PRODUCER.ID
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCER.DATE_OF_BIRTH
     *
     * @return the value of PUBLIC.PRODUCER.DATE_OF_BIRTH
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCER.DATE_OF_BIRTH
     *
     * @param dateOfBirth the value for PUBLIC.PRODUCER.DATE_OF_BIRTH
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCER.FIRST_NAME
     *
     * @return the value of PUBLIC.PRODUCER.FIRST_NAME
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCER.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.PRODUCER.FIRST_NAME
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PRODUCER.LAST_NAME
     *
     * @return the value of PUBLIC.PRODUCER.LAST_NAME
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PRODUCER.LAST_NAME
     *
     * @param lastName the value for PUBLIC.PRODUCER.LAST_NAME
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}