package psk1.assignment.myBatis.model;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROLE.ID
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROLE.ACTOR_NAME
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    private String actorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROLE.DESCRIPTION
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROLE.ROLE_NAME
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROLE.MOVIE_ID
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    private Integer movieId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROLE.ID
     *
     * @return the value of PUBLIC.ROLE.ID
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROLE.ID
     *
     * @param id the value for PUBLIC.ROLE.ID
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROLE.ACTOR_NAME
     *
     * @return the value of PUBLIC.ROLE.ACTOR_NAME
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public String getActorName() {
        return actorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROLE.ACTOR_NAME
     *
     * @param actorName the value for PUBLIC.ROLE.ACTOR_NAME
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public void setActorName(String actorName) {
        this.actorName = actorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROLE.DESCRIPTION
     *
     * @return the value of PUBLIC.ROLE.DESCRIPTION
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROLE.DESCRIPTION
     *
     * @param description the value for PUBLIC.ROLE.DESCRIPTION
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROLE.ROLE_NAME
     *
     * @return the value of PUBLIC.ROLE.ROLE_NAME
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROLE.ROLE_NAME
     *
     * @param roleName the value for PUBLIC.ROLE.ROLE_NAME
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROLE.MOVIE_ID
     *
     * @return the value of PUBLIC.ROLE.MOVIE_ID
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROLE.MOVIE_ID
     *
     * @param movieId the value for PUBLIC.ROLE.MOVIE_ID
     *
     * @mbg.generated Sat Mar 20 19:25:49 EET 2021
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }
}